## 网站设置
# 标题
title: Lin Jin's Blog
# 选项卡标题
SEOTitle: KinLin | KinLin‘s   Blog
# 首页背景图片
header-img: img/theworld.jpg
# 邮箱设置
email: jlscut@gmail.com
# 网站介绍
description: "I guess it comes down to a simple choice:get busy living or get busy dying."
# 关键词
keyword: "camera, c++, dev"
# 博客访问链接
#url: "https://aigq.me"
# '/blog' if your blog hosted on 'host/blog'
baseurl: ""

## 侧边栏设置
# 是否开启侧边栏 true 开始 false 关闭
sidebar: true
# 侧边栏描述语句
sidebar-about-description: "Improve Yourself"
# 侧边栏头像
sidebar-avatar: /img/bestrong.jpg

## 社交网站设置
RSS: false
# 微博 打开个人主页截取用户编号 例如个人主页网址为https://weibo.com/u/5089298519 填写 5089298519
#weibo_username:
# 知乎个人页面 填写用户名
#zhihu_username:
# GitHub个人页面 填写用户名
#github_username:
# facebook个人页面 填写用户名
#facebook_username:
# 简书个人页面截取用户编号 与微博同理
#jianshu_username:
# twitter个人页面 填写用户名
#twitter_username:

## 构建设置
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

## Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

## Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

## 评论系统
# Disqus（https://disqus.com/）
# disqus_username: superZhoudalu

## Gitalk
gitalk:
  #是否开启Gitalk评论
  enable: false
  #生成的clientID
  #clientID:
  #生成的clientSecret
  #clientSecret:
  #仓库名称
  #repo:
  #github用户名
  #owner:
  #  admin:
  #是否启用类似FB的阴影遮罩
  #  distractionFreeMode: true

## 统计
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-135281137-1'
# 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
#ga_domain: https://aigq.me

## 标签设置
# 是否使用首页标签
featured-tags: true
# 相同标签数量大于这个数，才会出现在首页
featured-condition-size: 0

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

## 友情链接
friends: [
    {
        #        title: "",
        #        href: ""
    }
]
